### PR TITLE
Harmony concatenation service tutorial notebook

### PR DESCRIPTION
**Pull request by skorper**
Tutorial demonstrating Harmony concatenation via Concise. This notebook only demonstrates Concise usage, and does not demonstrate Concise + L2SS-Py chain usage.

### CODE REVIEW

**Review by frankinspace — APPROVED** [review]
Awesome! Looks good to me. We should start using the harmony-py client in our tutorials https://github.com/nasa/harmony-py but for now this matches the other tutorials so it's ok.

**Comment by skorper** [comment]
@frankinspace Ah I keep forgetting that exists! I will definitely change that in the future. That will be a good opportunity to see if Harmony-py already supports concatenation

**Comment by frankinspace** [comment]
I don't think it does, so probably another reason to stick with url building for the moment

**Comment by frankinspace** [comment]
Well look at that, it does https://github.com/nasa/harmony-py/blob/main/harmony/harmony.py#L156

**Pull request merged**
