### PR TITLE
MODIS ARD datacube

### PR DESCRIPTION
**Pull request by edshred2000**
General housekeeping and updated gdalWarp() to use bilinear interpolation

### CODE REVIEW

**Comment by edshred2000** [comment]
Looks good.

**Comment by jjmcnelis** [comment]
Ed can you confirm that this is the latest version of your notebook? https://github.com/edshred2000/tutorials/blob/master/notebooks/MODIS_L2P_SST_DataCube.ipynb 

I'm afraid to try to sort the ipynb conflicts here inside the GitHub interface. So I will close this one and submit a new PR that's in sync with podaac/tutorials master branch.

**Comment by edshred2000** [comment]
Yes. I did confirm

I did not realize there were so many conflicts. Were most of them because of tutorial output like filenames and other code output ? I know that can make it messy.

-- Ed


From: Jack McNelis ***@***.***>
Reply-To: podaac/tutorials ***@***.***>
Date: Tuesday, April 6, 2021 at 3:31 PM
To: podaac/tutorials ***@***.***>
Cc: "Armstrong, Edward M (US 398P)" ***@***.***>, Assign ***@***.***>
Subject: [EXTERNAL] Re: [podaac/tutorials] MODIS ARD datacube (#13)


Ed can you confirm that this is the latest version of your notebook? https://github.com/edshred2000/tutorials/blob/master/notebooks/MODIS_L2P_SST_DataCube.ipynb<https://urldefense.us/v3/__https:/github.com/edshred2000/tutorials/blob/master/notebooks/MODIS_L2P_SST_DataCube.ipynb__;!!PvBDto6Hs4WbVuu7!dcd0sbR1M3zvyv--TmQUnQvOKV4xLyxpRw1HLfkZq75BqhZxMoavNfgrkJ6XnwMiPX_hLmrgVp5i$>

I'm afraid to try to sort the ipynb conflicts here inside the GitHub interface. So I will close this one and submit a new PR that's in sync with podaac/tutorials master branch.

**Comment by mgangl** [comment]
did you pull the updated master notebook from podaac/tutorials into your fork? This looks like you did more copy/pasting into your notebook instead of using the git commands to update your fork. See https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork. I'd recommend using the git commands to update a forked notebook, or when you're done with your code, delete _your_ tutorials fork and then re-fork it when necessary. Right now we have parallel notebooks with a common ancestor of ~february ish. That means, to your notebook, my updates 18 days ago ever happened.

**Comment by edshred2000** [comment]
Thanks Mike.  I probably made some mistakes in the logistics.   Jack is helping me out.

-- Ed


From: mgangl ***@***.***>
Reply-To: podaac/tutorials ***@***.***>
Date: Wednesday, April 7, 2021 at 5:13 AM
To: podaac/tutorials ***@***.***>
Cc: "Armstrong, Edward M (US 398P)" ***@***.***>, Assign ***@***.***>
Subject: [EXTERNAL] Re: [podaac/tutorials] MODIS ARD datacube (#13)


did you pull the updated master notebook from podaac/tutorials into your fork? This looks like you did more copy/pasting into your notebook instead of using the git commands to update your fork. See https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork<https://urldefense.us/v3/__https:/docs.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork__;!!PvBDto6Hs4WbVuu7!Ykxy9uQz7o8z039JZwM8r7v0pejRpGkUwxE7u0CUgGGh4YFYX_qWgO79tfgqpbcXveklC9hlOjhU$>. I'd recommend using the git commands to update a forked notebook, or when you're done with your code, delete your tutorials fork and then re-fork it when necessary. Right now we have parallel notebooks with a common ancestor of ~february ish. That means, to your notebook, my updates 18 days ago ever happened.

**Pull request closed without merging**
