### PR TITLE
add notebook to query cmr and get s3 links for a collections

### PR DESCRIPTION
**Pull request by sliu008**
- Created a notebook to show how to get list of s3 links from a cmr query

### CODE REVIEW

**Comment by sliu008** [comment]
https://github.com/podaac/tutorials/blob/cmr_s3_links/notebooks/podaac_cmr_s3_links.ipynb

**Review by jamesfwood — APPROVED** [review]

**Comment by jinbow** [comment]
@sliu008, This is great. My suggestions for improvement:
1. Add a parameter search by short_name
2. Capability of using .netrc file for auto-authentication
3. Add a description how to get the EDL token.
4. Add a description where to find the concept id

**Comment by sliu008** [comment]
> @sliu008, This is great. My suggestions for improvement:
> 
> 1. Add a parameter search by short_name
> 2. Capability of using .netrc file for auto-authentication
> 3. Add a description how to get the EDL token.
> 4. Add a description where to find the concept id

@jinbow I made the suggest changes you wanted, i added code that gets the EDL token and a collection concept id by a collection short name.

**Comment by jinbow** [comment]
Simon, this is great. I tested it and it worked on my laptop, beautiful! One minor request. Can you change the last line to "display(s3_links)"? It will produce nicer printout list.

**Pull request merged**
